-- MySQL Script generated by MySQL Workbench
-- Tue Oct  6 11:25:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbPrototipo2P
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbPrototipo2P
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbPrototipo2P` DEFAULT CHARACTER SET utf8 ;
USE `dbPrototipo2P` ;

-- -----------------------------------------------------
-- Table `dbPrototipo2P`.`tbl_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPrototipo2P`.`tbl_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPrototipo2P`.`tbl_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPrototipo2P`.`tbl_producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NULL,
  `precio_producto` DECIMAL(5) NULL,
  `fk_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_tbl_producto_tbl_categoria1_idx` (`fk_id_categoria` ASC)  ,
  CONSTRAINT `fk_tbl_producto_tbl_categoria1`
    FOREIGN KEY (`fk_id_categoria`)
    REFERENCES `dbPrototipo2P`.`tbl_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPrototipo2P`.`tbl_puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPrototipo2P`.`tbl_puesto` (
  `id_puesto` INT NOT NULL AUTO_INCREMENT,
  `nombre_puesto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_puesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPrototipo2P`.`tbl_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPrototipo2P`.`tbl_empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre_empleado` VARCHAR(45) NULL,
  `apellido_empleado` VARCHAR(45) NULL,
  `dpi_empleado` INT NULL,
  `fk_id_puesto` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_tbl_empleado_tbl_puesto_idx` (`fk_id_puesto` ASC)  ,
  CONSTRAINT `fk_tbl_empleado_tbl_puesto`
    FOREIGN KEY (`fk_id_puesto`)
    REFERENCES `dbPrototipo2P`.`tbl_puesto` (`id_puesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPrototipo2P`.`tbl_bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPrototipo2P`.`tbl_bodega` (
  `id_bodega` INT NOT NULL AUTO_INCREMENT,
  `nombre_bodega` VARCHAR(45) NULL,
  `direccion_bodega` VARCHAR(45) NULL,
  PRIMARY KEY (`id_bodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPrototipo2P`.`tbl_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPrototipo2P`.`tbl_pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `cantidad_pedido` INT NULL,
  `fecha_pedido` VARCHAR(45) NULL,
  `fk_id_bodega` INT NOT NULL,
  `fk_id_empleado` INT NOT NULL,
  `fk_id_producto` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_tbl_pedido_tbl_bodega1_idx` (`fk_id_bodega` ASC)  ,
  INDEX `fk_tbl_pedido_tbl_empleado1_idx` (`fk_id_empleado` ASC)  ,
  INDEX `fk_tbl_pedido_tbl_producto1_idx` (`fk_id_producto` ASC)  ,
  CONSTRAINT `fk_tbl_pedido_tbl_bodega1`
    FOREIGN KEY (`fk_id_bodega`)
    REFERENCES `dbPrototipo2P`.`tbl_bodega` (`id_bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_tbl_empleado1`
    FOREIGN KEY (`fk_id_empleado`)
    REFERENCES `dbPrototipo2P`.`tbl_empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_tbl_producto1`
    FOREIGN KEY (`fk_id_producto`)
    REFERENCES `dbPrototipo2P`.`tbl_producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
